# Generated by Django 4.2.7 on 2023-12-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rent',
            fields=[
                ('bike_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=100)),
                ('bike_rent', models.BigIntegerField()),
            ],
        ),
    ]
